govCMS/govcmslagoon

.docker/images/govcms7/scripts/govcms-deploy, modules/lagoon/govcms_lagoon/govcms_lagoon.info, modules/lagoon/govcms_lagoon/govcms_lagoon.install
The `govcms_lagoon` module can be used to introduce platform specific dependencies and common configuration.
=> Add govcms_lagoon module

.docker/images/govcms7/scripts/govcms-deploy, modules/lagoon/govcms_lagoon/govcms_lagoon.module
Deploy script needs to disable before uninstall.
=> D7 requires a .module file to be a module.

.circleci/config.yml
If amazeeio-network already exists (such as running circleci build locally) the process will fail.
Added a `|| true` as per https://stackoverflow.com/questions/48643466/docker-create-network-should-ignore-existing-network
=> Don't fail if amazeeio-network exists

.docker/images/govcms7/scripts/govcms-deploy
Aligns with latest changes in govcms8lagoon, bringing support for `govcms-deploy` in local environments.
Supports new `LAGOON_ENVIRONMENT_TYPE` to allow running on local development environments. Stage File Proxy to be enabled on all (cloud + local).
=> Enable Stage File Proxy in all non-prod environments.

.docker/images/govcms7/settings/settings.php
`fast_404` should ignore the private files path rather than the public files path based on readme from the module.
https://cgit.drupalcode.org/fast_404/tree/README.TXT?id=7.x-1.5#n124
=> Updated fast_404 config to ignore private files.

.docker/Dockerfile.govcms7, .docker/Dockerfile.php
Updates default `max_input_vars` to `2000` also investigating increasing this config in the lagoon images.
=> Added custom PHP_MAX_INPUT_VARS env var in code and cli images.

.docker/images/govcms7/scripts/govcms-deploy
If the Drupal was previously installed but during the run of the  deployment script for some reason Drupal couldn't be bootstraped (like a short hickup, not reachable database server, etc.), this was assumed to be a non installed Drupal and an sql-sync was initiated.
This is super rare (as we assumed that the sql-sync then also would fail, but it seems that it was possible).
This new script does it better:
It only tries an sql-sync when drush command didn't fail and only if the database is completely empty, so we don't rely anymore on drupal being able to be boostraped or not.
=> Better check if Drupal is already installed

.docker/Dockerfile.nginx-drupal, .docker/images/nginx/no_robots_govcms_host.conf
proof:
```
[drupal-example]cli-drupal:/app$ curl nginx:8080/robots.txt  -H "Host: blub.govcms.gov.au"
User-agent: *
Disallow: /
[drupal-example]cli-drupal:/app$ curl nginx:8080/robots.txt  -H "Host: bla.blub.govcms.gov.au"
User-agent: *
Disallow: /
[drupal-example]cli-drupal:/app$ curl nginx:8080/robots.txt  -H "Host: www.blub.govcms.gov.au"
User-agent: *
Disallow: /
[drupal-example]cli-drupal:/app$ curl nginx:8080/robots.txt  -H "Host: www.govcms.gov.au"
<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL "http://www.govcms.gov.au/robots.txt" was not found on this server.</p></body></html>
[drupal-example]cli-drupal:/app$ curl nginx:8080/robots.txt  -H "Host: www.govcms.com"
<!DOCTYPE html><html><head><title>404 Not …
```
=> Return with a `Disallow: /` for non-production URLs

.docker/images/govcms7/settings/settings.php
Disables redis by default and can be reenabled by adding the `ENABLE_REDIS` to `lagoon-env`.
*redis will be disabled on all sites by default*
=> Added condition to enable redis config.

.docker/images/nginx/helpers/expires.conf
Pending an updated to the akamai_file_purge module, we should set the expiry time back to 30m to allow Akamai to get newer versions of static files.
This should be reverted once we are able to purge cache for these static assets.
=> Change binary file expiry to 30m default

.docker/Dockerfile.solr, docker-compose.yml, tests/goss/goss.solr.yaml
Decoupling `govcmslagoon/solr` from govcms project.
Builds from `amazeeio/solr:6.6` and adds config from the `cli` image.
Added goss tests:
- ensure solr core has been created.
- ensure the correct schema is set.
- ensure customisations to `solrconfig.xml` are set.
=> Add custom solr image with tests.

.circleci/config.yml
Adding a pair of steps to CircleCI to install a dummy site, then get a Drush status, and Drush pm:list to serve as a visual check that updates have applied properly.
In govcms/govcms the build log will contain this, but it may be worth adding anyway?
=> Add a release/version check step into CircleCI for confirmation

.docker/images/nginx/helpers/acsf_redirects.conf
A regex change to improve NetID matching in the NGINX redirects
ref: GOVCMSD7-89
=> improve NetID matching in the NGINX redirects

.docker/Dockerfile.govcms7
unfortunately 10.3 has a bug running mysqldumps against RDS: https://jira.mariadb.org/browse/MDEV-17429
=> downgrade to mariadb-client 10.2

.docker/images/govcms7/scripts/govcms-deploy
to fix deploy errors with sites, remove drush rr from govcms-deploy
=> remove drush rr

.docker/Dockerfile.govcms7, .docker/Dockerfile.test, tests/goss/goss.govcms7.yaml, tests/goss/goss.test.yaml
This PR fixes:
* GOVCMSD7-228 - Add findutils to govcmslagoon cli and test images (amazeeio/lagoon#1077)
* no longer need to specify mysql-client version - available upstream (https://github.com/amazeeio/lagoon/commit/4913081c518686feffb33ce17d409fe7e0c1b7d1)
* GOVCMSD7-200 - pin drupal module version numbers in govcmslagoon
=> Feature/version pinning, mysql-client version and findutils addition

.docker/images/govcms7/scripts/govcms-deploy
This PR unblocks https://github.com/govCMS/govCMS/pull/827
See https://github.com/govCMS/govCMS/pull/827 for more information.
The redirect module is currently patched to version `7101` and is preventing upstream database updates with the same identifier with different purpose. The existing database update simply removed table rows based on a set of conditions, where the officially released update introduces a new field.
This will allow the `redirect` module to be updated to `7.x-1.0-rc3` from `7.x-1.0-rc1` which will close a long-standing issue.
=> Revert schema version for redirect module

.docker/images/govcms7/scripts/govcms-deploy
- Updb implicitly clears caches after completion this will prevent an additional drush call.
=> Remove the superfluous drush cc all.

.gitignore, docker-compose.yml
This PR fixes an issue that without the `*default-volumes` being added into the php image, php effectively created it's own files volume, and didn't share it with NGINX.  In addition, this volume is mounted into the host for visibility whilst testing.
It also removes a legacy migration volume that is no longer needed.
*Note* that these changes only affect development/testing undertaken on the govcmslagoon repo, and have no effect on the downstream images created and consumed by GovCMS sites.
=> add shared files volume to php image and expose on host

.docker/Dockerfile.php, .docker/Dockerfile.test
- Clears composer cache after install.
- Installs apk packages without cache.
Using `composer clearcache` as composer could be configured to cache in different locations we use the composer command to clear cache.
@see https://github.com/composer/composer/pull/3175/files
=> Clear caches to reduce image size.

.docker/images/govcms7/scripts/govcms-deploy
As discussed, the PR contains the following changes:
- Remove the one-off fix to redirect module legacy issue
- Add a ```drush updb - y``` for PROD db synced across
- Run ```drush updb - y``` before ```drush en stage_file_proxy -y```
=> [GOVCMSD7-282] Improve govcms-deploy script

.docker/images/govcms7/scripts/govcms-deploy
Ordered dumps are good for readability (and diffing content); but bad for increased size on disk and import performance (every record is a single insert query instead of combined).
=> Remove ordered-dump flag.

.docker/images/govcms7/settings/settings.php
Allow overriding of the redis port and cache prefix without affecting current behaviour.
Projects will be able to customise the redis HOST, PORT and CACHE_PREFIX if required.
=> Added redis config for port and cache prefix.

.docker/images/govcms7/settings/settings.php
'0' was being treated as a falsey always so even with the correct environment variables set it would still use the binary.
- Adds a strict type check for !== false as getenv will return bool if the variable is not defined.
- Adds a looser catch by setting to a string of daemon so we can fallback if '0' is mistreated.
=> Update catch for CLAMAV_MODE

modules/lagoon/lagoon_search/lagoon_search.module
https://jira.gold.gov.au/jira/browse/GOVCMSD7-209
Lagoon Search module sets up the default Solr server when it gets enabled but it doesn't specify the "scheme" option as part of the default configuration. This produces a PHP notice when accessing the server settings page.
The scheme option is specified correctly in GovCMS D8: 
https://github.com/govCMS/govcms8lagoon/blob/master/modules/lagoon/lagoon_search/config/install/search_api.server.lagoon_solr.yml#L13
=> Added scheme to default Lagoon Solr server config.

.docker/images/govcms7/settings/production.settings.php, docker-compose.yml
Alters default max-age header to 1h with env var override.
=> Set max-age header to 1h by default.

.docker/images/govcms7/scripts/govcms-deploy, .docker/images/govcms7/settings/production.settings.php
Ensure database drop before sync.
=> Rolled back default max-age header to 900s.

.docker/Dockerfile.govcms7, .env.default
Updates required for `v7.x-3.11` builds to complete:
* Removal of `https://www.drupal.org/files/issues/drupal-500_exception_on_exception-12221055-6.patch` because of upstream merge in Drupal `7.67`.
* Update version reference
=> Additional requirements for 7.x.3.11

.docker/Dockerfile.nginx-drupal, .docker/images/nginx/drupal/favicon.conf, .docker/images/nginx/helpers/230-favicon.conf, tests/goss/goss.nginx-drupal.yaml
Adds a nginx config value to redirect /favicon to one provided by the profile if it does not exist. This happens when loading files (PDFs) or server errors as the browser will request /favicon.ico by default.
=> Added an nginx redirect to the default govcms favicon.

tests/goss/goss.php.yaml
* Remove dependency on eicar.org uptime (many failures in past due to network connectivity issue)
* Alter test file + approach (piped output was not working)
=> Fix clamav test.

.docker/images/govcms7/settings/settings.php
This PR allows a site to provide an optional FAST_404_EXTS variable to be able to override the default FAST_404 configuration.  This is useful where sites have specific needs for filetypes that are generally not used anywhere else in GovCMS.
This variable is controlled in PROD via the config_map, and can be set locally via a docker-compose.override.file and setting the variable in .env
```
version: '2.3'
services:
php:
environment:
FAST_404_EXTS: ${FAST_404_EXTS}
```
=> [GOVCMSD7-13] Add FAST_404_EXTS variable to allow per-site FAST_404 overrides

.docker/Dockerfile.govcms7, .docker/Dockerfile.php, .docker/images/govcms7/settings/settings.php, .docker/images/nginx/drupal/favicon.conf, .docker/images/nginx/helpers/000-client_max_body_size.conf, .docker/images/php/00-govcms.ini, .env.default, tests/goss/goss.nginx-drupal.yaml, tests/goss/goss.php.yaml
* [GOVCMSD7-310] Reduce maximum file upload to 256MB
* [GOVCMSD7-290] Remove superfluous GMP libraries
* [GOVCMSD7-13] Allow fast 404 overrides per project
* [NO-TICKET] Use latest ClamAV repository (edge)
* [NO-TICKET] Update to latest Lagoon images (1.3.1)
=> Draft release: 3.12.0

.docker/images/nginx/helpers/207-security-headers.conf, .docker/images/nginx/tests/src/SecurityHeadersTest.php
As per D8: https://github.com/govCMS/govcms8lagoon/pull/129
```
cli-drupal:/app$ curl -I http://nginx:8080/
HTTP/1.1 200 OK
Server: openresty
...
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
```
=> GOVCMSD7-329: Added default security headers.

.docker/images/php/00-govcms.ini
Noting that:
```
session.gc_divisor => 1000 => 1000
session.gc_probability => 1 => 1
```
GC will kick in 0.1% of the time at present, so on average you will need ~1000 hits at origin to trigger a session cleanup.
=> Increased session lifetime to 8h.

.docker/images/nginx/helpers/202-acsf_redirects.conf, .env.default
Legacy redirects are not enforcing https on the destination.
This updates theme file redirects to match the method used for public files.
=> Forced ssl redirects on acsf theme files.

.docker/images/nginx/helpers/202-acsf_redirects.conf, .docker/images/nginx/tests/bootstrap.php, .docker/images/nginx/tests/src/AcsfRedirectsTest.php, .env.default
Minor release to address an issue with mixed content warnings in browsers for some GovCMS 7 sites.
- Fixes an issue with theme files not redirecting to HTTPS causing mixed content warnings in browsers.
- Updates the Lagoon base images to 1.8.2 
Sites that utilised the legacy redirect for theme files were sometimes being served over HTTP which caused some browsers to report mixed content warnings and would cause newer browsers to not execute scripts that were served over HTTP. To resolve, all legacy file redirects will be forced to HTTPS.
- @stooit
=> Release 3.15.2

.env.default
This change will incorporate
* https://github.com/uselagoon/lagoon-images/releases/tag/21.3.0
* https://github.com/uselagoon/lagoon-images/releases/tag/21.2.2
Which at a high level will update:
* Update Alpine Linux to `3.12.5`
* PHP to version `7.3.27`
* The opt-in ability to use Nginx `rewrite_log`
* Allow `crond` to use a non-root working directory
* Add Nginx map hash configuration
=> Update the base images to reference the latest Lagoon images

.env.default
use true to activate xdebug instead of any string @tobybellwood (#251)
Install Blackfire Agent and Probe within php containers @Schnitzel (#249)
only accept true for $NEWRELIC_ENABLED @Schnitzel (#250)
Fail image build if composer checksum does not match. @marji (#241)
Adds mongodb-tools to toolbox image @bomoko (#247)
Prevent match in between the string @grappler (#202)
Ref: https://github.com/uselagoon/lagoon-images/releases/tag/21.7.0
=> [GOVCMSD7-422] update lagoon to 21.7.0 from 21.6.0

.gitlab-ci.yml
- Updates `when` condition to allow deploying multiarch images from `release/*` branches
=> Deploy beta images via CI
