- .docker/Dockerfile.acsf
changes correspond to modules removed in https://github.com/govCMS/govCMS/pull/732
> Add acquia+removed modules in dockerfile.acsf

- .docker/images/nginx/helpers/acsf_redirects.conf
To support https://github.com/govCMS/govcms7-scaffold/pull/3
> Custom themes will mount in sites/default/themes/custom.

- .docker/Dockerfile.govcms7
https://govdex.gov.au/jira/browse/GCMSLG-140
> Patch applied - re: akamai caching error

- .docker/Dockerfile.acsf
- .docker/Dockerfile.govcms7
- .docker/Dockerfile.mariadb-drupal
- .docker/Dockerfile.nginx-drupal
- .docker/Dockerfile.php
- .docker/Dockerfile.test
pin govcms7 docker image to 3.2
> pin govcmsdev docker images to 3.2

- .docker/Dockerfile.acsf
- .docker/Dockerfile.govcms7
- .docker/Dockerfile.mariadb-drupal
- .docker/Dockerfile.nginx-drupal
- .docker/Dockerfile.php
- .docker/Dockerfile.test
pin govcmsdev docker images to 3.3
> pin govcmsdev docker images to 3.3

- .docker/images/govcms7/scripts/govcms-deploy
Related
https://github.com/govCMS/govcms8-scaffold-paas/pull/8
https://github.com/govCMS/govcms8-scaffold/pull/16
https://github.com/govCMS/govcms7-scaffold-paas/pull/2
https://github.com/govCMS/govcms7-scaffold/pull/11
https://github.com/govCMS/govcms8lagoon/pull/73
https://github.com/govCMS/govcmslagoon/pull/99
> GOVCMS-3718: Env testing

- .docker/Dockerfile.php
- .docker/images/govcms7/settings/settings.php
- Adds clamav config to support running in daemon mode.
- Adds clamav host env var.
- Adds clamav port env var.
- Removes clamav from the PHP container.
> [GOVCMS-2408]: Updated clamav implementation to use daemon mode.

- .env.default
* Remove ACSF code and adding VBO fix back into govcms_tweaks module
> [GOVCMS-3786] 3.9.0 Release

- README.md
Sister of https://github.com/govCMS/govcms8lagoon/pull/64
> Improved docs.

- .env.default
- docker-compose.yml
https://www.php.net/supported-versions.php
PHP7.1 is EOL, active/security releases end Dec 1.
> Updated PHP to 7.2.

- .docker/Dockerfile.govcms7
Fixes a broken URL path which shouldn't have been committed.
> Change namespace reference previously used for testing.

- .docker/Dockerfile.govcms7
- .docker/Dockerfile.test
- .docker/images/govcms7/mariadb-client.cnf
https://github.com/govCMS/govcms8lagoon/pull/104
> Update max_allowed_packet for client connections.

- .docker/images/nginx/helpers/202-acsf_redirects.conf
> [GOVCMSD7-316] Hotfix for sites falsely reporting as insecure by browsers

- docker-compose.yml
Will follow up with formalities shortly
> Update default for PHP_IMAGE_VERSION used by docker-compose.

- .env.default
Pin lagoon image version to 1.5.0
> Pin lagoon image version to 1.5.0

- .docker/images/nginx/tests/bootstrap.php
- .docker/images/nginx/tests/src/AcsfRedirectsTest.php
- Updates header retrieval to include location
- Validates location includes https
> Validate the location has https.

- .ahoy.yml
- .docker/Dockerfile.govcms7
- .docker/Dockerfile.test
- .docker/images/nginx/tests/bootstrap.php
- .docker/images/nginx/tests/src/AcsfRedirectsTest.php
- .gitlab-ci.yml
- Adds gitlab CI configuration to run scheduled jobs
> [GOVCMS-5205]: Gitlab CI integration for module audit generation

- .docker/images/govcms7/scripts/govcms-deploy
Resolve sql-dump error after recent upgrade.
> Added deployment levers.

- .docker/images/nginx/helpers/203-expires.conf
- Adds CSV to the extension list to allow per-project controlled cache expires
> [GOVCMS-5739]: Add CSV to binary file extension list.

- .env.default
Update GOVCMS_PROJECT_VERSION to 7.x-3.22
> Update GovCMS D7 version

- .env.default
https://github.com/uselagoon/lagoon-images/releases/tag/22.1.0
> [GOVCMSD7-444] Update lagoon base images to 22.1.0 from 21.12.2

- .env.default
https://github.com/uselagoon/lagoon-images/releases/tag/22.2.0
> [GOVCMSD7-448] Update lagoon base images to 22.2.0 from 22.1.0

- .env.default
https://github.com/uselagoon/lagoon-images/releases/tag/22.4.0
> [GOVCMSD7-454] Update lagoon base images to 22.4.0 from 22.2.0

- .env.default
https://github.com/uselagoon/lagoon-images/releases/tag/22.7.0
> [GOVCMSD7-461] Update lagoon base images to 22.7.0 from 22.5.0
